// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

#include "hal.h"
#include "mongoose_glue.h"

// This function blocks forever. Call it in a
// separate RTOS task. Give that task 8k stack space.
static void run_mongoose(void *args) {
  mongoose_init();
  for (;;) {
    mongoose_poll();
  }
  (void) args;
}

int main(void) {
  // Cross-platform hardware init
  hal_init();
  MG_INFO(("HAL initialised, starting firmware..."));

  // Start tasks. NOTE: stack sizes are in 32-bit words
  xTaskCreate(run_mongoose, "mongoose", 2048, 0, configMAX_PRIORITIES - 1, NULL);

  vTaskStartScheduler();  // This blocks
  return 0;
}
